name: successapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  calendar_date_picker2: ^0.5.5
  connectivity: ^3.0.6
  connectivity_plus: ^6.0.2
  flutter:
    sdk: flutter
  flutter_timezone: ^1.0.8
  http: ^1.2.1
  shared_preferences: ^2.2.3
  syncfusion_flutter_calendar: ^25.1.39

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
